server:
  lister: "localhost:8080"

mysql:
  db : mysql
  dbHost : localhost
  dbPort : 3306
  dbUser : mangosteen
  dbPassWord : 123456
  dbName : giligili_go
redis:
  redisDb : redis
  redisAddr : localhost:6379
  redisPw :
  redisDbName :
gin_mode: debug
